/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lectureinitializer;

import org.testng.*;
import org.testng.annotations.*;

import java.io.*;

public class MainTest {

    @Test
    public void mainTest() throws IOException {
        Assert.assertEquals(true, true);
    }

}
